Neos:
  Neos:
    nodeTypes:
      groups:
        content:
          position: 100
          label: 'Content'
        component:
          position: 200
          label: 'Component'
        property:
          position: 300
          label: 'Property'

Sitegeist:
  Silhouettes:
    properties:
      webco:
        text:
          none:
            type: string
            ui:
              inlineEditable: TRUE
              inline:
                editor: 'ckeditor5'
                editorOptions:
                  placeholder: i18n
                  autoparagraph: false
                  formatting:
                    strong: false
                    em: false
                    u: false
                    sub: false
                    sup: false
                    del: false
                    p: true
                    h1: false
                    h2: false
                    h3: false
                    h4: false
                    h5: false
                    h6: false
                    pre: false
                    underline: false
                    strikethrough: false
                    removeFormat: true
                    left: false
                    right: false
                    center: false
                    justify: false
                    table: false
                    ol: false
                    ul: false
                    a: false
                    b: false
                    i: false
          highlight:
            type: string
            ui:
              inlineEditable: TRUE
              inline:
                editor: 'ckeditor5'
                editorOptions:
                  placeholder: i18n
                  autoparagraph: false
                  formatting:
                    strong: false
                    em: false
                    u: false
                    sub: false
                    sup: false
                    del: false
                    p: false
                    h1: false
                    h2: false
                    h3: false
                    h4: false
                    h5: false
                    h6: false
                    pre: false
                    underline: false
                    strikethrough: false
                    removeFormat: true
                    left: false
                    right: false
                    center: false
                    justify: false
                    table: false
                    ol: false
                    ul: false
                    a: false
                    b: true
                    i: true
        image:
          custom:
            ui:
              reloadIfChanged: TRUE
              inspector:
                editorOptions:
                  features:
                    crop: TRUE
                  crop:
                    aspectRatio:
                      options:
                        square: ~
                        fourFive: ~
                        fiveSeven: ~
                        twoThree: ~
                        fourThree: ~
                        sixteenNine: ~
                      enableOriginal: false
                      allowCustom: true
