Neos:
  Neos:
    fusion:
      autoInclude:
        'Webandco.NodeTypes': TRUE
    nodeTypes:
      groups:
        content:
          position: 100
          label: 'Content'
        component:
          position: 200
          label: 'Component'
        property:
          position: 300
          label: 'Property'
